- name: reload docker daemon
  systemd:
    name: docker
    masked: false
    enabled: yes
    daemon-reload: yes
    state: restarted

- name: reload journald
  systemd:
    name: systemd-journald
    masked: false
    enabled: yes
    daemon-reload: no
    state: restarted

- name: restart etcd
  systemd:
    name: etcd
    masked: false
    enabled: yes
    daemon-reload: yes
    state: restarted
